In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing various datasets which are present in Sklearn.datasets

### IRIS DATASET

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
X,y = iris.data , iris.target

In [5]:
X[:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y[:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
len(X)

150

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
rfc = RandomForestClassifier()

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [12]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [13]:
y_pred_rfc = rfc.predict(X_test)

In [14]:
from sklearn.metrics import classification_report , mean_absolute_error , mean_squared_error

In [15]:
print(classification_report(y_test,y_pred_rfc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.95      0.95      0.95        20
           2       0.92      0.92      0.92        12

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



### Fetch California Housing

In [16]:
from sklearn.datasets import fetch_california_housing

In [17]:
fch = fetch_california_housing()

In [18]:
X , y = fch.data , fch.target

In [19]:
len(X)

20640

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [21]:
X[:6]
#y[:6]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 4.03680000e+00,  5.20000000e+01,  4.76165803e+00,
         1.10362694e+00,  4.13000000e+02,  2.13989637e+00,
         3.78500000e+01, -1.22250000e+02]])

In [22]:
from sklearn.ensemble import HistGradientBoostingRegressor , RandomForestRegressor

In [23]:
hgbr = HistGradientBoostingRegressor( max_leaf_nodes=15, random_state=101, early_stopping=False)

In [24]:
hgbr.fit(X_train,y_train)

HistGradientBoostingRegressor(early_stopping=False, max_leaf_nodes=15,
                              random_state=101)

In [25]:
y_pred_hgbr = hgbr.predict(X_test)

In [26]:
#print(classification_report(y_test,y_pred_hgbr))

In [27]:
y_pred_hgbr.round()

array([4., 5., 1., ..., 1., 1., 2.])

In [28]:
y_test

array([4.062  , 5.00001, 1.229  , ..., 1.363  , 0.608  , 2.31   ])

In [29]:
mae=mean_absolute_error(y_test,y_pred_hgbr)
mae

0.3388528267865489

In [30]:
mse=np.sqrt(mean_squared_error(y_test,y_pred_hgbr))
mse

0.5093152536659094

In [31]:
y_test.mean()

2.076627592054263

In [32]:
100*mae / y_test.mean()

16.317457597264486

In [33]:
import joblib
N_CORES = joblib.cpu_count(only_physical_cores=True)
N_CORES

4

In [34]:
rfr = RandomForestRegressor(min_samples_leaf=5, random_state=101, n_jobs=N_CORES)

In [35]:
rfr.fit(X_train,y_train)

RandomForestRegressor(min_samples_leaf=5, n_jobs=4, random_state=101)

In [36]:
y_pred_rfr = rfr.predict(X_test)

In [37]:
mae=mean_absolute_error(y_test,y_pred_rfr)

In [38]:
mae

0.3472489629245128

In [39]:
mse=np.sqrt(mean_squared_error(y_test,y_pred_rfr))
mse

0.5374384774002952

In [40]:
100*mae / y_test.mean()

16.72177352613347

### Dump SVMlight File

In [41]:
from sklearn.datasets import dump_svmlight_file ,make_classification

In [42]:
X , y = make_classification(random_state=0)

In [43]:
output_file = 'my_datasets.dump_svmlight_file'

In [44]:
dump_svmlight_file(X,y,output_file)

In [45]:
X.shape

(100, 20)

In [46]:
y.shape

(100,)

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [48]:
X[0]

array([-0.03926799,  0.13191176, -0.21120598, -1.2141474 ,  1.05004467,
       -0.42132759,  0.76877064,  0.87569568,  2.45122972, -0.48024204,
       -2.13264106, -0.52325094,  0.70869527, -1.98056559, -1.36516288,
       -0.94893281,  1.94709864,  1.97698901,  1.02122474, -0.46931074])

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
lr = LinearRegression()

In [51]:
lr.fit(X_train,y_train)

LinearRegression()

In [52]:
y_pred_lr = lr.predict(X_test)

In [53]:
mean_absolute_error(y_test,y_pred_lr)

0.36026047341970746

In [54]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0])

In [55]:
np.absolute(y_pred_lr.round())

array([1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [56]:
from sklearn.naive_bayes import GaussianNB

In [57]:
gnb = GaussianNB()

In [58]:
gnb.fit(X_train,y_train)

GaussianNB()

In [59]:
y_pred_gnb = gnb.predict(X_test)

In [60]:
y_pred_gnb

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0])

In [61]:
from sklearn.metrics import confusion_matrix

In [62]:
confusion_matrix(y_test,y_pred_gnb)

array([[14,  2],
       [ 3, 11]], dtype=int64)

In [63]:
print(classification_report(y_test,y_pred_gnb))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85        16
           1       0.85      0.79      0.81        14

    accuracy                           0.83        30
   macro avg       0.83      0.83      0.83        30
weighted avg       0.83      0.83      0.83        30



### Load Breast Cancer

In [64]:
from sklearn.datasets import load_breast_cancer

In [65]:
load_breast_cancer_data = load_breast_cancer()

In [66]:
X , y = load_breast_cancer_data.data , load_breast_cancer_data.target

In [67]:
len(X)

569

In [68]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [69]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [73]:
gnb.fit(X_train,y_train)

GaussianNB()

In [74]:
y_predict = gnb.predict(X_test)

In [75]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.92      0.88      0.90        66
           1       0.93      0.95      0.94       105

    accuracy                           0.92       171
   macro avg       0.92      0.92      0.92       171
weighted avg       0.92      0.92      0.92       171



In [76]:
confusion_matrix(y_test,y_predict)

array([[ 58,   8],
       [  5, 100]], dtype=int64)